version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run container
          command: |
            docker run -t -d -w /opt/repo -v `pwd`:/opt/repo:rw --privileged --network host --name mytest ubuntu
      - run:
          name: Execute command
          command: |
            docker exec mytest bash -lc "echo it works"
      - run:
          name: Cleanup
          when: always
          command: |
            docker kill mytest
            docker rm mytest --force
